### ISSUE TITLE
A11y Implementation

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#201]
This issue helps tracks the big picture progress of the description design, description implementation, and implementation of alternative input. Sound and adaptive features are incorporated only at a high-level here, though could be added as we move forward and learn more.

# A11y Features 
**Checked features are being worked on for this sim**
- [x] Alternative Input -  (done)
    - [x] Mobile A11y included
- [x] Interactive Description
    - Syan roughly sketched out rough state descriptions early 2018
    -  @Matthew-Moore240 started July 2019 to complete the design
    - Interactive Description Design Complete: April 7, 2020 (except hot key for Pause/Play)
- [x] Sonification - (Started: ??) (Completed: March 31, 2020)
- [x] Zoom/Magnify feature included
- [x] Dev Test Complete (Started May 12, 2020, Completed: May 28, 2020)
- [x] RC Test, July 9th, 2020 [QA#513](https://github.com/phetsims/QA/issues/513)
  - https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.2/phet/molecules-and-light_all_phet.html
- [x] RC Spot Check, August 4th, 2020 [QA#520](https://github.com/phetsims/QA/issues/520#issuecomment-668667094)
  - https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-rc.3/phet/molecules-and-light_all_phet.html
- [x] Published, August 12, 2020

# A11y Design
- [x] Multimodal Features folder created in PhET Sim Design folder. Sub-folders (Description and Sound) created as needed. A11y Design Main design doc created in Description sub-folder (Date: )
- [x] Link to [MAL Interactive Description Design Doc](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.i184lm885tbh)
- [x] This is **not** a multi-screen sim! (Multi-screen sims may need to additional links for each screen)  

# A11y Design Prep
- [x] Main Sim Design reviewed for learning goals
- [ ] Teaching materials reviewed
- [ ] Reviewed model properties with Main Developer or A11y Developer
- [ ] Identify visual enhancements that deviate from model (e.g. "hollywooding")

# Parallel DOM (PDOM)
**Checked items have PDOM structures identified & determined**
- [x] Dynamic objects that warrant their own name and description in the Play Area
- [x] All interactive objects and their PhET types (e.g., sliders, buttons, etc.)
- [x] New interaction types (i.e., new a11y types) in this sims, or check:
  - [x] Tricky buttons 
    - [x] On/Off switch for light source (new design pattern) #296 - used multiple techniques to scaffold the Light Source button: `aria-role="switch"` with `aria-checked` to created an on-off switch experience for AT users, context responses to communicate photons are on/off, and context responses to scaffold interaction when the sim is paused. 
    - [x] Play/Pause button for playing and pausing the sim (used context responses to scaffold interaction  with Step Forward button, and to indicate when Light Source is off.)
    - [x] Step Forward button (a tricky button) - resolved with help text, context responses, and custom shortcut keys

## [State Descriptions](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.lfzscx53fh1b)
**Checked items drafted & ready for implementation**
### Static State Descriptions
- [x] Static screen summary
- [x] Initial sim-specific interaction hint (place in own paragraph)
- [x] Headings for objects/groups in Play Area
- [x] Labels for interactive elements
- [x] Heading outline & Focus Order 
- [x] Help text for interactive elements 
- [x] Description for Light Spectrum Diagram - final check #340 

### [Dynamic State Descriptions](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.pmtozxml2p5f)
**Checked items completed in design document**
- [x] PDOM section of Design Doc contains 1 clear example of each dynamic description
- [x] More examples and possible edge cases have been explored for:
    - [x] Dynamic screen summary (i.e., brief state-of-the-sim)
    - [x] Dynamic states for identified dynamic objects (can add list to this issue)
- [x] Dynamic parameters (scales and approximate ranges) for dynamic objects ready
    - [x] Special case parameters or phrases identified (dynamic screen summary, dynamic states)

## Responsive Descriptions
**Checked items drafted & ready for implementation**
### Object Responses
This sim has no sliders, only buttons and radio buttons. There is no `aria-valuetext` in this sim. Object responses are communicated natively via labels and states.

### [Context Responses](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit?pli=1#heading=h.p4mpdjt09p0b)
**[Molecule Excitation/Vibration Responses](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.je2pnc7qy5er)**
- Different modes of exploration verified
  - [x] Responses at normal speed 
  - [x] Responses on slow motion
  - [x] Responses for Step Forward  

### [UI Context Responses ](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit?pli=1#heading=h.pttsu0l2kwji)
**Checked items ready for implementation**
  - [x] Context responses for items in Control Area (Sim Speed radios, Pause/Play buttons, Step Forward button)
  - [x] Common code responses (e.g., Reset All, Mute Sound) verified
  
## Description Design Testing
- [x]  n/a

# A11y Implementation
**Checked items verified by designer**
### Static State Descriptions (Screen Summary)
- [x] H1 for sim title
- [x] Tab order correct
- [x] Sim Regions & H2 Headings (Play Area, Control Area, Sim Resources)
- [x] Static part of screen summary
  - [x] Iterations based on design changes verified.
- [x] Initial sim-specific interaction hint provided in own paragraph
- [x] Keyboard Shortcuts interaction hint (PART OF COMMON CODE) 

### Static State Descriptions (Play Area)
- [x] Sim-specific H3's for sim objects (or none for this sim)
- [x] Interactions are accessible (i.e., have accessible names, keyboard accessible)
- [x] Help text for interactive objects

### Static Descriptions (Control Area) 
- [x] Sim-specific H3 & H4 for Timing Controls & Sim Speeds
- [x] Interactions are accessible (i.e., names, keyboard accessible)
- [x] Help text for Timing Controls (Sim Speeds & Pause/Play, Step Forward)
- [x] Reset All button & reset response

### Sim Resources (Sim Resources)
- [x] Keyboard Shortcuts dialog completed
    - [x] Keyboard Shortcuts dialog accessible
	- [x] Keyboard Shortcuts button added
- [x] Mute Sound button (added when sound is added to main sim repo)

### Dynamic State Descriptions
**Add or remove details as needed**
**Dynamic Screen Summary**
- [x] Phrases work with all parameters
- [x] Capitalization verified
- [x] Punctuation verified
- [x] Edge cases verified (Phase 4 of break apart - #323)
- [x] Photon passes response for non-reactive pairs - #333 - considered after final design interviews  

**Play Area Object Descriptions**
- [x] no `aria-valuetext` in this sim

### Object Responses
**Light Source**
- [x] interaction change to on/off switch - (no longer any `aria-valuetext`)
- Reasonable communication of on/off states verified in all AT
  - [x] VoiceOver & Safari - works perfectly with focus and state changes
  - [x] NVDA & Firefox
  - [x] JAWS & Chrome 

### Complex Context Responses (often aria-live regions)
**Name Context Responses and details as needed**

### [UI Context Responses](https://docs.google.com/document/d/1r9D3vq4QvmmXkQ5G6HexpybUv_vL6LrYFb3wgPfUdWg/edit#heading=h.pttsu0l2kwji)
  - [x] Pause/Play button responses, verified
  - [ ] Custom global Shortcut Key for Pause/Play investigated & reviewed (see phetsims/scenery-phet/issues/571). 
- Custom Keyboard Shortcuts added for Timing Controls. In early interview a Shortcut key for Pause/Play was suggested. In final interviews a shortcut for Step Forward was suggested. These shortcuts add a lot of usability to the Timing Controls widget. 
    - [x] #336 - Pause/Play (Alt + K) & Step Forward bigger steps (Alt + L) 
    - [x] #338  - Updates to Keyboard Shortcuts dialog to include Alt + L
    - [x] Once all is verified and implemented, create issue for **new design pattern for Timing Controls**
        -  https://github.com/phetsims/scenery-phet/issues/610

# Other A11y ToDo's
**Make a website issues to update URL to working prototype on the website's [Accessible Sims page](https://phet.colorado.edu/en/accessibility/prototypes)**
- [x] Once there is a working prototype
- [x] At Dev Testing
- [x] At RC Testing
- [x] At publication

**Other Features & Items (e.g., Mobile A11y features?)**
- Nothing too difficult in this sim, just buttons and radio buttons

**Check Credits**
- [x] Verified additions to Team: Wanda Diaz Merced, Brett Fiedler, Matthew Moore, Taliesin Smith, Brianna Tomlinson, Syan Zhou
- [x] Verified Sound Design: Ashton Morris, Mike Winters

**Once Evaluation begins**
- [x] Ensure interviews are recorded to this sim's interview spreadsheet

**During QA or just after publication**
- [ ] Clean and polish up A11y design doc
- [x] List out main design challenges (if any and if necessary)
- [x] List out lessons learned from this sim (e.g., found focus issues for iOS)
- [x] Create issues to document new A11y Design Patterns (i.e., on/off switch, timing controls) - what repos?
- [x] Suggest improvements to THIS issue template
  - Add a new section, "Create Issues to Document New Design Patterns"
      - New Design Patterns for this sim are posted in the following issues:
          - On/Off switch: https://github.com/phetsims/sun/issues/603
          - Timing Controls: https://github.com/phetsims/scenery-phet/issues/610

**Housekeeping notes (e.g., significant changes to Checklist (optional)**
**Items to check as March 11**
- [x] create issue re changes to PDOM due to slider/button change  - #302
- [x] check off items above and note where descriptions need to be reviewed (e.g., the wording of all the responses for normal, slow, and step forward)
- [x] change and create issue to update content of keyboard shortcut dialog - #303
- [x] create issue to review light spectrum dialog content - #304

See https://github.com/phetsims/molecules-and-light/issues/180 as the previous issue tracking descriptions (pre checklist). 
Assigning to designer @Matthew-phet to bring this list up to date.

**Comment by terracoda** [comment]
Posted by @BLFiedler in duplicate issue #294 

> #270  Sound Features Video for MAL issue Linked here.

**Comment by terracoda** [comment]
@jessegreenberg, in https://github.com/phetsims/chipper/issues/954#issuecomment-655786009, @zepumph commented that the issue (https://github.com/phetsims/chipper/issues/954) was no longer blocking and people needing sha's for should talk to @chrisklus to get the they need.

I am marking that issue as done for the MAL check list. Hopefully, you can put the sim in RC now :-)
