### ISSUE TITLE
Adjust/Update State Descriptions (PDOM) affected by interaction change to Light Source

### ISSUE THREAD

**Issue by terracoda** [phetsims/molecules-and-light#302]
Changes to the Light Source interaction are in progress in #295 and #296. @terracoda and @Matthew-Moore240 need to review PDOM and address necessary changes to:
- [x] created issues for changes to screen summary - references to slider and rates (#306, #307, #308, #301)
- [x] created issues for observation window (if any) - (#301)
- [x] created issue for new interaction name and help text (and code #296)
- [x] created issue for the dynamic state of the sim sentence (#312)

**Comment by terracoda** [comment]
@Matthew-Moore240, we also need to remove the rates in the sentence that describes the "dynamic state of the sim". I will created an issue for that, too.

**Comment by jessegreenberg** [comment]
@Matthew-Moore240 @terracoda can this issue be closed?

**Comment by terracoda** [comment]
All issues I was tracking in this issue are closed except for #295. Once that issue is closed, this issue can be closed.

**Comment by terracoda** [comment]
All issues noted in this issue have been addressed. Closing.
